/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Addon } from "./Addon";
import { AddonCountArgs } from "./AddonCountArgs";
import { AddonFindManyArgs } from "./AddonFindManyArgs";
import { AddonFindUniqueArgs } from "./AddonFindUniqueArgs";
import { DeleteAddonArgs } from "./DeleteAddonArgs";
import { AddonService } from "../addon.service";
@graphql.Resolver(() => Addon)
export class AddonResolverBase {
  constructor(protected readonly service: AddonService) {}

  async _addonsMeta(
    @graphql.Args() args: AddonCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Addon])
  async addons(@graphql.Args() args: AddonFindManyArgs): Promise<Addon[]> {
    return this.service.addons(args);
  }

  @graphql.Query(() => Addon, { nullable: true })
  async addon(
    @graphql.Args() args: AddonFindUniqueArgs
  ): Promise<Addon | null> {
    const result = await this.service.addon(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Addon)
  async deleteAddon(
    @graphql.Args() args: DeleteAddonArgs
  ): Promise<Addon | null> {
    try {
      return await this.service.deleteAddon(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
