/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Offer } from "./Offer";
import { OfferCountArgs } from "./OfferCountArgs";
import { OfferFindManyArgs } from "./OfferFindManyArgs";
import { OfferFindUniqueArgs } from "./OfferFindUniqueArgs";
import { DeleteOfferArgs } from "./DeleteOfferArgs";
import { OfferService } from "../offer.service";
@graphql.Resolver(() => Offer)
export class OfferResolverBase {
  constructor(protected readonly service: OfferService) {}

  async _offersMeta(
    @graphql.Args() args: OfferCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Offer])
  async offers(@graphql.Args() args: OfferFindManyArgs): Promise<Offer[]> {
    return this.service.offers(args);
  }

  @graphql.Query(() => Offer, { nullable: true })
  async offer(
    @graphql.Args() args: OfferFindUniqueArgs
  ): Promise<Offer | null> {
    const result = await this.service.offer(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Offer)
  async deleteOffer(
    @graphql.Args() args: DeleteOfferArgs
  ): Promise<Offer | null> {
    try {
      return await this.service.deleteOffer(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
